#!/bin/sh

# Categories

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'startups' --data '{"name":"Startups","description":"Tech startup coverage that breaks down the funding, growth, and long-term trajectory of companies across every stage and industry, including climate, crypto, fintech, SaaS, transportation, and consumer tech."}'

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'svb-2023-crash' --data '{"name":"SVB 2023 crash","description":"In early March a run on Silicon Valley Bank led to its takeover by the Federal government. During the following weekend, the startup and venture capital industry around the world was in crisis, as SVB banked both companies and their backers. The American government announced before the week started that depositors would be whole, and liquid on Monday, March 13. The story is not over. SVB affiliates around the world are still being sorted out, other banks are under pressure, and a second crypto-friendly bank was also taken over by the government. TechCrunch is working to better understand how founders are impacted in the wake of the initial crisis, and what is ahead."}'

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'venture' --data '{"name":"Venture","description":"Our venture capital coverage features all the VCs, the VC-backed startups, and the investment trends that founders, investors, students, corp development pros, academics - and anyone else interested in the way that tech is transforming the world - should be tracking."}'

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'security' --data '{"name":"Security","description":"Cybersecurity encompasses investigative reporting and analysis on the latest security breaches, hacks and cyberattacks around the globe."}'

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'robotics-ai' --data '{"name":"Robotics & AI","description":"Bleeding edge robotics companies and AI startups, focused on a wide range of automation categories, including logotics, ag-tech, delivery, healthcare, home robotics and food service, along with the latest university and laboratory research into soft robotics, nano robotics and more."}'

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'cryptocurrency' --data '{"name":"Crypto","description":"Cryptocurrency coverage and news on Bitcoin, Ethereum and the blockchain startups building the future of crypto, web3 using tokens and NFTs."}'

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'apps' --data '{"name":"Apps","description":"The app economy continues to grow, having produced a record number of downloads and consumer spending across both the iOS and Google Play stores. Keep up with this fast-moving industry in one place, with the latest from the world of apps, including news, updates, startup fundings, mergers and acquisitions, and much more."}'

appwrite databases createDocument --databaseId 'default' --collectionId 'categories' --documentId 'events' --data '{"name":"Events","description":"Be the first to hear about the latest TechCrunch events and opportunities."}'

# Articles

appwrite storage createBucket --bucketId 'thumbnails' --name 'thumbnails' --fileSecurity 'true' --permissions 'read("any")' --permissions 'create("users")' --permissions 'update("team:admins")' --permissions 'delete("team:admins")'  --maximumFileSize '5242880' --allowedFileExtensions 'png' --allowedFileExtensions 'jpg' --allowedFileExtensions 'jpeg'

appwrite storage createFile --bucketId 'thumbnails' --fileId 'article1' --file './images/article1.png'

appwrite databases createDocument --databaseId 'default' --collectionId 'articles' --documentId 'article1' --data '{"title":"OpenAI ChatGPT Plus subscription launches in India","author":"Jagmeet Singh","categoryId":"robotics-ai","imageId":"article1","content":"ChatGPT Plus, the subscription service to access OpenAI text-generating AI, is now available in India. ChatGPT Plus features GPT-4, the refined AI model that OpenAI launched earlier this week.\nThe paid tier provides customers with early access to new features including GPT-4. Introduced in the U.S. in February after being in an early preview for a few weeks, ChatGPT Plus is available at a monthly subscription price of $20. A subscription allows a customer to use ChatGPT even during peak-usage hours, get faster responses and priority access to new features and improvements.\nOpenAI continues to also offer a free version of ChatGPT — although with a few restrictions — on its website. If you do not wish to pay for access, you can still enjoy the ChatGPT experience through the Bing search engine.\nOpenAI initially had a waitlist for users to access ChatGPT Plus. However, shortly after its release, the startup made the subscription service available to all users. The service aims to help OpenAI monetize ChatGPT, which has become viral and gained mass attraction for its AI-based conversational experience in recent months.\nUnderstandably, ChatGPT has also grappled with some controversies and bans due to its nature and sophistication of its human-like responses that can be deceptive. Its advanced text conversational capabilities have certainly appealed to the masses and even attracted OpenAI’s early investor Microsoft to integrate the experience within its services. Competitors including Baidu and Google have also started to build similar conversational AI experiences."}'
